---
title: "TCGA Kinase mRNA Analysis"
output: github_document
---

```{r, echo = FALSE}
library(FirebrowseR)
library(DarkKinaseTools)
library(BerginskiRMisc)
library(readr)
library(here)
library(tidyverse)
library(progress)
library(synapser)
```

## Data Collection/Loading

This notebook assumes that you have already run the kinase_CNV_download.Rmd
document and successfully collected the kinase_CNV.rds file.

```{r data_collection, cache=TRUE}
#check if a data file has been made with these results, if so, go ahead and load
#it, otherwise WARNING!
if (file.exists(here('mRNA_analysis','data','kinase_mRNA.rds'))) {
  kinase_mRNA = read_rds(here('mRNA_analysis','data','kinase_mRNA.rds'))
} else {
  warning("Couldn't find the kinase_mRNA.rds file, did you run the Kinase_mRNA_download document?")
}
```

## Data Organization/Analysis

The mRNA data is organized by patient sample with the primary summary statistic the log2 expression level.

```{r data_analysis}
#Some of the expression_log2 values are saved as None, which I'm going to
#interpret as a zero and replace those values as such.

kinase_mRNA$expression_log2[kinase_mRNA$expression_log2 == "None"] = 0
kinase_mRNA$expression_log2 = as.numeric(kinase_mRNA$expression_log2)

kinase_mRNA_summary = kinase_mRNA %>%
  filter(sample_type != "NT") %>%
  group_by(cohort,gene) %>% 
  summarise(average_expression = mean(expression_log2,na.rm=T))

readr::write_csv(kinase_mRNA_summary,here('mRNA_analysis','data','kinase_mRNA_summary_TCGA.csv'))

synLogin()
synStore(File(path=here('mRNA_analysis','data','kinase_mRNA_summary.csv'), parent='syn13363433'))
```

```{r kinase_correlations}
kinase_matrix = kinase_mRNA %>% 
  select(tcga_participant_barcode,gene,expression_log2,cohort,sample_type) %>%
  mutate(barcode_cohort = paste0(tcga_participant_barcode,'-',cohort,'-',sample_type)) %>%
  select(barcode_cohort,gene,expression_log2) %>%
  spread(gene,expression_log2)

kinase_correlations = cor(kinase_matrix[,2:dim(kinase_matrix)[2]])

write.csv(kinase_correlations,here('mRNA_analysis/data/kinase_correlations.csv'))
```